### ISSUE TITLE
World map: illegal move allowed

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#225]
From a member:

> Vostok fleets have NO coastline with DdU, and cannot move there, and thus should not be able to issue supports to DdU.

However, it looks like this is currently possible:

<img width="707" alt="screen shot 2016-02-21 at 2 07 51 am" src="https://cloud.githubusercontent.com/assets/914369/13197338/f41f7ae0-d83f-11e5-988b-a2b972a7aedd.png">

Probably the adjudicator is confused because there's a land connection between the two provinces, and there's no specified coasts.

**Comment by TimothyJones** [comment]
@Sleepcap - we have the same borders as vDiplomacy now, so this problem will exist on your fork too. Can we fix it by giving both provinces single coast lines with no connections to each other?

**Comment by diptobi1** [comment]
@TimothyJones - Were you able to reproduce this? I tried to enter such an order for the fleet in Vostok and (as expected) even the JS-interface doesn't offer a support for Norwegian Dependency (I assumed the army in the picture came from that territory):
![bildschirmfoto 2016-02-22 um 18 27 00](https://cloud.githubusercontent.com/assets/7372519/13227028/ce530560-d994-11e5-9d97-4f8283942f9d.png)

The adjudicator itself doesn't check borders, that's already and only done by the userOrder classes in board/orders/, that check the user input. Therefor you can actually produce anything like above even without any borders between the territories, e.g. a support from an army in Moscow for move heading to Galicia. You just have to manipulate the orders directly in data base:
![bildschirmfoto 2016-02-22 um 18 40 09](https://cloud.githubusercontent.com/assets/7372519/13227127/5de37660-d995-11e5-80e9-9c177bc92939.png)

I used a (nearly) clean webdip installation that is just about 3 or 4 weeks old, so I don't think there should be any differences caused by different versions.

**Comment by TimothyJones** [comment]
The live install here:

http://webdiplomacy.net/board.php?gameID=171307&viewArchive=Orders#index55

showed the problem. However, it looks like we didn't correctly flush the border cache for the variant after accepting the recent border changes from vDip - which I have now done. The live install was behind the repository, and I hadn't realised.

Thanks for the investigation - very much appreciated!
