### ISSUE TITLE
Reveal CD'd players at end of game

### ISSUE THREAD

**Issue by yangkky** [kestasjk/webDiplomacy#226]
At the end of a game, the mod-only field at the bottom that shows the identity of CD'd players should be made viewable by all users. There's no reason for this to be kept secret.

**Comment by 18zhenjaso** [comment]
I'll begin working on this one as soon as I can.

**Comment by TimothyJones** [comment]
Most of the code is already there, since mods have this feature. We just have to expose it to regular users.

A couple of gotchas:

* In anon games, usernames should be hidden (but the CD can still be shown without the name)
* Moderators should be able to see who has CDed in anon games that they themselves are not in.

**Comment by 18zhenjaso** [comment]
Yes I understand. I see why it's been a little bit difficult to do the code
- pretty tedious.

It'll take some time for me to get to finishing it? I won't have any
definitive deadline, right?

Also, I would like to know, how many people are there like you, developing
the code?

Thanks Tim.

Thanks,
Jason
