### ISSUE TITLE
How does vDip decide who the winner is?

### ISSUE THREAD

**Issue by plund** [kestasjk/webDiplomacy#262]
# Bug report

We find it strange that one player is declared winner in a game that ends autumn 1902 with an equal center count 3-3. 

Questions:
* Why is this game not declared to be a draw? 
* What are the "other" critera for how this decision is made? 
* Is there some help page on vDip or webdiplomacy that describes this? (if not, it would be nice if such a help page could be created.)

See: http://www.vdiplomacy.com/board.php?gameID=32471

## Expected behaviour

We expected the game to be declared a Draw.

## Actual behaviour

Germany was declared winner.

## Steps to reproduce

As in our test game http://www.vdiplomacy.com/board.php?gameID=32471

1 - set turns to 4
2 - make sure a unit is disloged in the autumn 1902 with viable retreat options into centeres it does not own.
3 - The unit is not given the chance to retreat into those centers.

**Comment by TimothyJones** [comment]
Hi Peter! Thanks for these reports. I appreciate you taking the time to write them out.

Unfortunately, we don't look after vDiplomacy- this repository is only for the core webdiplomacy code. I'm not sure what their bug report process is, but you can find their repository listed as a fork of this one.

**Comment by TimothyJones** [comment]
This is a good report of the retreats bug (#196). I'm travelling at the moment, but I'll check the other issues you've reported against the core source when I get home.

**Comment by plund** [comment]
I post links to these 2 issues on to the vdiplomacy forum and ask there how to report stuff to them. since the github project Sleepcap/vDiplomacy does not have an "Issues" tab. (That fact could in itself be considered a bug :)

**Comment by plund** [comment]
Link to my vDip forum post
http://www.vdiplomacy.com/forum.php?viewthread=72993#72993

**Comment by plund** [comment]
But these question in this issue is also relevant for webDiplomacy. 
Is it not always a draw on webDiplomacy, if 2 powers end up on the same top center count? If not is there a help page?

**Comment by Enriador** [comment]
There is no bug at all. The game maker simply didn't read/explained you the rules.

From the "New game" section:

"The winning player is decided by who has the most SCs after that turn's diplomacy phase. If 2 or more player have the same SCs at the end of the game, the game checks for the turn before, and so on. If player's SC counts are the same throughout the whole game the winner is decided at random. "

Since there was no isolate leader, the game checked for the turn before - and saw that Germany had 4 centers against Italy's 3 in that turn. Hence, Germany is the rightful victor.

**Comment by TimothyJones** [comment]
Thanks @Enriador, you're correct. This situation cannot occur on webdiplomacy.
