### ISSUE TITLE
Works with PHP 7.2 ?

### ISSUE THREAD

**Issue by agony09** [kestasjk/webDiplomacy#351]
Hello, i have a short question.
This script works in PHP 7.2 vers too ?
best regards

**Comment by jmo1121109** [comment]
The site is currently running PHP Version: 7.0.32-0ubuntu0.16.04.1
Anything higher has not been tested.

**Comment by Sleepcap** [comment]
My webhoster will remove PHP-7.0 support at the ned of the year.

**Comment by jmo1121109** [comment]
Hi @Sleepcap, I'm not familiar with php upgrades. Is that an area you're comfortable with? If so I'd be happy to help with testing out and vetting any PR pushed with it. Otherwise I'll get in touch with Kestas and have him prioritize that as his project for the year. I expect he'll get at least a couple days to dig into site code before the end of the year.
