### ISSUE TITLE
Map that works for colourblind users

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#48]
The current map performs poorly for colourblind users. We should add the option to display a better map to colourblind users.

vDip currently has this feature, we could pull it from them.

**Comment by Sleepcap** [comment]
I took the javascript-code from here: http://mudcu.be/labs/Color-Vision/Javascript/Color.Vision.Daltonize.js and made a PHP version of it, because I do not know JS that good. I would highly recommend to use this and do the rendering client-side.

**Comment by TimothyJones** [comment]
Ah, great! Thanks. I'll use that directly, I think.

Do you have a structure for saving user settings on vDip, or do you just use the User table? The user table is getting pretty large, so I'm keen to move to a different solution.

**Comment by Sleepcap** [comment]
As I try not to change the code too much I just use the User-table.
But if you want to change this just go ahead. If you make a new table please make the code so I easily add my vDip "preferences" there too. (for example, I put each variable in all possible places in separate lines, so it's much easier to apply patches.)

**Comment by gneils** [comment]
Could you point me to the PHP code?  I'm interested in taking a look.

**Comment by Sleepcap** [comment]
https://github.com/Sleepcap/vDiplomacy/blob/master/map/drawMap.php#L1286

**Comment by gneils** [comment]
One idea is to use safe colors.  This gets rid of an unnecessary setting. 

Here is one possible color combination that works in cartography:

#a50026
#d73027
#f46d43
#fdae61
#fee090
#ffffbf
#e0f3f8
#abd9e9
#74add1
#4575b4
#313695
I used the Color Brewer 2.0 to generate these colors.
http://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=11

Let's change th

**Comment by kestasjk** [comment]
One issue is that in an extreme case where everyone had their own color scheme they would each need their own map cache, or they would need their maps generated on the fly. We should be getting a free server upgrade later this year but need to conserve resources still.

If there was some user provided JS function to change around the colors in a JPG.. Or if map SVG output worked this would be straightforward.
Tricky.

Rgds,
Kestas 

-----Original Message-----

**Comment by Sleepcap** [comment]
Hi kestas. There is a "user provided JS function to change around the colors in a JPG"
http://mudcu.be/labs/Color-Vision/Javascript/Color.Vision.Daltonize.js

**Comment by gneils** [comment]
I'm advocating for one color schema with color blind friendly colors. Many folks that are color blind can not see the difference between red and green.  They can tell the difference between shades of red, shades of blue and textures.  The easiest, simplest way to enhance the map would be to 1) differentiate things by shades and textures.  Dark red and dark green look similar to someone that is color blind. Dark red and light green don't look similar.  Throw in some texture and the problem is solved for everyone. This avoids personal settings, javascript post fixes, image caches, programming, and maintenance. 

I propose the following steps:

1) Choose better default colors

2) Then see if additional work needs to be done.

**Comment by Sleepcap** [comment]
But we have variants with 18+ countries too...
At least the common color-scheme should  consider 12 or more colors...

**Comment by kestasjk** [comment]
Thanks Oli, that might be a good way to do it. Gniels I think we shouldn't design the site as if everyone has the worst possible case of colorblindness, since that would be too constrictive given that color js the main way countries are distinguished and a color blind person may be very sensitive to changes in the hues they can see which a full color vision person might not be.

I do think an option to allow users to choose alternative CSS for the main site, since I understand there is a blue/green colorblindness which would suck with our colors. 
Then there should be alternative color choices offered by variants for the colors they use, and the tricky part will be doing this in a way that wont need a new map cache for each color scheme.

This would be my approach anyway. It could then also be used for people who just want to use the board colors they're more familiar with (I.e. The white Russia color setup in more recent boards)

Rgds,
Kestas

-----Original Message-----

**Comment by TimothyJones** [comment]
I'm working on integrating the Javascript that Oli linked.

**Comment by TimothyJones** [comment]
Fixed! For red-green and blue-yellow colourblindness, there are now options under the user's settings page.
