### ISSUE TITLE
Make TD powers reveal anonymous players

### ISSUE THREAD

**Issue by TimothyJones** [kestasjk/webDiplomacy#51]
If a player has TD powers over a game, they can't see who the players are if the game is anonymous.

We should change this so that they can.

**Comment by TimothyJones** [comment]
As part of this change, the `directorUserID`s need to be pulled out of board.php and into objects/game.php, as per a todo in board.php.

**Comment by negaffney** [comment]
We don't allow members to TD games they're in by policy anyway. It would probably be worthwhile to add a check on that in the actual mod action to give TD powers, but that can be its own issue.

**Comment by TimothyJones** [comment]
Are you saying you *want* TD powers to see through anon in games they're in?

Seems like that's likely to lead to more error-prone code - I think the logic should be "Do you have mod powers in this game?" and that check looks to see if you're a TD. Then we'd only have one concept - and the differences between moderators and TDs would go away.

**Comment by jmo1121109** [comment]
Yeah my general thought is we're going to run into more cases where a teacher wants to TD a school group and doesn't want the students to know who's who, but still wants to be able to reorder countries, use TD tools effectively then we will run into situations where a mod incorrectly grants someone TD access in their own game. Since we can fix the 2nd case manually, but cannot fix the first case manually, allowing TD's to see through anonymity is the choice I went with. Ideally we'd have an extra option or a teacher mode eventually, but that's a further down the line enhancement.

**Comment by jmo1121109** [comment]
The other thought on differences between TD and mod is the way the the moderator tools are presented. For a TD they are nicely arranged below the game in a at least somewhat explained format. For mods this isn't the case, and I'm not sure we'd want to have both layouts for both user types. Not positive though, that might be something for the mod team to consider, if they would like seeing those tool below games like TD's currently do.

**Comment by jmo1121109** [comment]
This was done in a prior PR.
