### ISSUE TITLE
Division By 0 Error if Everyone is Status Left

### ISSUE THREAD

**Issue by jmo1121109** [kestasjk/webDiplomacy#518]
I've run into this a few times through site history. If everyone in a game went into CD during the last phase the scoring system tries to do a division by the # of active members in the game (aka 0) which throws an error while trying to give a winner points. In this scenario the game should enter "crashed" status before trying to declare a winner.

**Comment by Sleepcap** [comment]
Looks like the "new" excused delay kicks more people out of the game at the same time...
Esp. with smaller variants that get abandoned by all (usually new players) after a few rounds.
IMHO the game should _not_ enter crashed status, but end in a "draw" with all the remaining players involved to keep mod/admin involvement to a minimum.

**Comment by jmo1121109** [comment]
I am fine with @Sleepcap's proposal. Less mod work is always nice.

**Comment by Sleepcap** [comment]
I have a patch already. Will test this later and submit a patch.

**Comment by Sleepcap** [comment]
The problem is a bit more complex and the how to resolve this needs some more discussion.
For a draw we need to set the newly CDed players back to "Playing".
1. Should we count a missed-turn for these (I would say yes)?
2. Should we include the players that CDed a turn earlier in the draw too (I would say no)?

**Comment by Sleepcap** [comment]
With further inspection I found that the problem is _not_ all players removed at the same time, but the "resetMinimumBet" funktion.
So it's more important to make this funktion failure-proof.
The next question is:  Should we take care of these "abandoned" games too, or leave them "open" for takeovers..? And if we end the game how to distribute the draw (see my last reply)?

**Comment by jmo1121109** [comment]
I am wondering if the right action is to cancel the game. Because cancel is when for everyone loses interest in the game cause something went wrong, which is exactly what has happened if everyone just left it. I don't think it is fair to let someone take over, click ready, and win the game instantly.

**Comment by Sleepcap** [comment]
A cancel removes every database entries of the game, so it might be problematic to trace all these NMRs later. So I think a draw is the better solution. And unusually a few people are already defeated, so a draw would show this too. 

Programming this is much cleaner/easier if we include all Left players, not just the most recent ones.

**Comment by jmo1121109** [comment]
Solved by @Sleepcap's last patch.
