### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by yeager-j** [kestasjk/webDiplomacy#656]
# Bug report

Error occurs when I attempt to register my first user after setting up a private server.

```
Error: "count(): Parameter must be an array or an object that implements Countable"
Raised: "/register/processUserForm.php"
Line: "79"
```

I looked through the source code but I'm not a PHP guy so I'm a little clueless. I also tried searching the GitHub Issues with no luck. It's probably a really stupid oversight on my part, but any help would be greatly appreciated.

Here's phpinfo:

![4750c0721477a4f02a73049be20510c3](https://user-images.githubusercontent.com/16469198/75846880-96dbcf00-5dab-11ea-8441-6bbacba3fac6.png)

**Comment by diptobi1** [comment]
This is because webdip cannot be run on php 7.2 or higher at the moment. Try downgrading to php 7.0 or 7.1. Or if that is not possible, you can check out the following pull request https://github.com/kestasjk/webDiplomacy/pull/654 too. The request does not yet seem to include a fix for the line that has thrown your error though.

**Comment by jmo1121109** [comment]
This has been solved, php 7+ now works on the code base
