### ISSUE TITLE
wD_GameMessages_Redacted table does not exist

### ISSUE THREAD

**Issue by c-flaherty** [kestasjk/webDiplomacy#740]
# Bug report

[`wD_GameMessages_Redacted` table does not exist](https://github.com/kestasjk/webDiplomacy/blob/a36469257a858a54921f71e9c8c31b4b4bcfda38/api/responses/game_state.php#L392)

The latest version of the codebase on `master` tries to pull messages from a table called `wD_GameMessages_Redacted`. It seems to me that the idea is that this table is created by running a script (perhaps invoked by a cron job every N minutes) to query `wD_GameMessages` and copy over rows to `wD_GameMessages_Redacted` after some redaction algorithm has been applied. However, there is currently (1) no database update script in `install/` to create this table, and (2) no script to actually populate it. As a temporary fix to run `master` locally, I changed `wD_GameMessages_Redacted` to `wD_GameMessages` in this line. 

Two possibles fixes for this:
1) Provide a database update script as well the redaction script (is it possible to provide the redaction script without introducing risk that it could be used by bad actors to learn how to un-redact tokens?)
2) Add some conditional logic here that queries `wD_GameMessages_Redacted` if it exists or `wD_GameMessages` if it does not.

**Comment by kestasjk** [comment]
Hi, unfortunately the redaction code isn't currently available, and if it was you would need to use it on your own database of unredacted Diplomacy game messages (as large as possible; we have a few million), since that is the input to the system to allow it to redact with confidence; it does all sort of analysis of other text, word frequencies etc; without a message database the redaction system would just be a dictionary check.

If you're not interested in redaction and just want to be able to retrieve unredacted game messages via json then we will need to make a change. I would use this code, just make sure it only requests from the unredacted table if the requesting user isn't a bot and doesn't have an API key.

**Comment by kestasjk** [comment]
Hey, I've added that table into the install script fyi, but the redaction code won't be available for a while yet
