### ISSUE TITLE
Latest code does not support php 5.2, 5.3

### ISSUE THREAD

**Issue by c-flaherty** [kestasjk/webDiplomacy#742]
Currently, the `README.txt` says, webDiplomacy supports "PHP 5.2 to 7.0". However, I personally ran into issues using PHP 5.3. 

For example, the array constructor syntax `[...]` does not work with php versions 5.2 and older (instead you need to use `array(...)`). We use the bracket syntax in several places such as these: https://github.com/kestasjk/webDiplomacy/blob/master/index.php#L831
https://github.com/kestasjk/webDiplomacy/blob/master/lib/html.php#L399

Should we consider not supporting PHP 5.2 and 5.3 anymore? If the above are truly the only issues, then it is an easy fix to change these few callsites to the legacy array constructor syntax. There might be other issues though -- these were just the few I found.

**Comment by kestasjk** [comment]
Hi Colin,

Hadn't spotted that new syntax being used, but I think we should give more importance to keeping up to date and being good for new developers rather than supporting old PHP versions. I'm not too worried about webDip not being compatible with a wide range of platforms / versions etc; it's not really meant to be installed by end users after all.

We should update the readme though; I think the best thing would be to recommend the versions we use on the official site, since that's always going to be fully supported, and I doubt anyone is going to test the system on different combinations of legacy versions anytime soon. At the moment we're on PHP 7.4, with cli,common,curl,fpm,gd,igbinary,json,mbstring,memcached,msgpack,mysql,opcache,readline,xml, MariaDB 10.3, Apache 2.4, Ubuntu 20.04 , so if you aim for that you can't go wrong.
