### ISSUE TITLE
Update-script for 1.36 only as CLI?

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#86]
I can't run CLI-commands from my webhoster.
Is it possible to make this accessible from the admin-interface too?

**Comment by TimothyJones** [comment]
Ah, I hadn't thought of that. I made it CLI, since it's only supposed to be only run once. Perhaps it should be part of install/install.php (to be run automatically when the DB version changes), or perhaps it should be an entry in the Admin panel. Or perhaps I should rewrite it so it can be run more than once.

The script is designed to "forgive" moderator forced CDs -one of the things it does is parse the admin log to find forced CDs, and forgive them. However, when the CD was forced by a tournament director, we don't have all the information required to find the CD entry in the CD table. So it decrements the "deletedCDs" column. We don't want to do this multiple times, and there's not really a good way of determining whether it's been done before.

This probably needs a bit of thinking about.

**Comment by TimothyJones** [comment]
I think this is no longer necessary? Feel free to reopen if I've got that wrong.
